### ISSUE TITLE
Require exifr not found

### ISSUE THREAD

**Issue by luispereira** [remvee/exifr#44]
I'm using `require 'exifr'` on my script on windows 10 although when I'm running the script it always gives: 
``require': cannot load such file -- exifr`

Although, if I do irb and then require 'exifr' on my command line it works.
my env:
 - RUBYGEMS VERSION: 2.2.3
 - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x64-mingw32]

Am I doing anything wrong here?

**Comment by remvee** [comment]
Hi Luis, I have no experience with ruby on windows but I am pretty sure you're doing something wrong and I am very sure the exifr gem is not the problem.  You're probably using a different ruby when you're running a script or you using bundler without exifr in the gemfile or something else.  Try your luck on one of the ruby related mailinglists or stackoverflow.
