### ISSUE TITLE
can't dup NilClass when using Cloudinary

### ISSUE THREAD

**Issue by bakashyn** [remvee/exifr#45]
Everything works fine in local storage. But when i using Cloudinary, it returned 'can't dup NilClass'.
`EXIFR::JPEG.new(@picture.link.path).model`

Inspect of @picture.link
`#<PictureUploader:0x007f60919555d0 @model=#<Picture id: 40, name: "IMG_9998", description: "AY", link: "dquft9uacgyahdxat4nx.jpg", created_at: "2016-04-09 03:45:25", updated_at: "2016-04-09 03:45:25">, @mounted_as=:link, @file=#<Cloudinary::CarrierWave::CloudinaryFile:0x007f6091955508 @uploader=#<PictureUploader:0x007f60919555d0 ...>, @identifier="dquft9uacgyahdxat4nx.jpg", @filename="dquft9uacgyahdxat4nx.jpg", @version=nil, @storage_type=nil, @resource_type="image", @public_id="dquft9uacgyahdxat4nx", @format="jpg">, @stored_public_id="dquft9uacgyahdxat4nx", @public_id="dquft9uacgyahdxat4nx", @stored_version=nil, @original_filename="dquft9uacgyahdxat4nx.jpg">
`

change .path to .filename isnt woking, return no such file or dir

Anyone knows how to use Exifr + Cloudinary

**Comment by remvee** [comment]
Try the cloudinary documentation to find out how to read the uploaded file.  EXIFR accepts an IO object too.

BTW this is an issue tracker not a forum.
