### ISSUE TITLE
Title Tag missing

### ISSUE THREAD

**Issue by tuxflo** [remvee/exifr#53]
Hi!
I'm using exifr as a great jekyll plugin ( https://github.com/benib/jekyll-exiftag). However while reading the description out of an image using `image_description` works great, I'm unable to read the Title information of an image. Exiftool (`exiftool test.jpg | grep "Title"`) gives me the following information of the image:
```
Title                           : Some Mountains and Trees
```
I already tried `image_title` and `title`.
Thanks in advance!

**Comment by remvee** [comment]
Unfortunately, there's no "title" tag in the EXIF spec, there's only "ImageDescription" (see page 28 of the [EXIF 2.3 specification](http://cipa.jp/std/documents/e/DC-008-2012_E.pdf)).  Exiftool supports vendor specific tags/information, this library does (and will) not.

It's also possible your title comes from XMP information, exiftool support that too.  You could try [amberbit/xmp](https://github.com/amberbit/xmp) to pull it out.
