### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by iroshiva** [remvee/exifr#64]
Hi !

I'm trying to use exifr with active storage and dropzone

I put the gem exifr in the gemfile
I set the require `require 'exifr/jpeg'` in a method create where i create the blob and attach him to my Model.

When i try to use `EXIFR::JPEG.new(blob).width` i get this error: `NoMethodError (undefined method `getbyte' for #<EXIFR::JPEG::Reader:0x0000564af877a080>):`

Can somebody can tell me why ??

Thx

**Comment by remvee** [comment]
From the [documentation](https://remvee.github.io/exifr/api/EXIFR/JPEG.html#method-c-new):

> +file+ is a filename or an IO object.  Hint: use StringIO when working with slurped data like blobs.

I don't know what your `blob` var holds but probably no filename or `IO` object.
