### ISSUE TITLE
Failure to read truncated EXIF/TIFF IFD entry

### ISSUE THREAD

**Issue by cgunther** [remvee/exifr#68]
Using the attached image (below), when I try to read it via `EXIFR::JPEG.new(path)`, I get "NoMethodError: undefined method `<' for nil:NilClass". I've confirmed this using the latest code on the master branch.

The traceback is:
```
Traceback (most recent call last):
	 9: from /Users/cgunther/Code/exifr/lib/exifr/jpeg.rb:34:in `initialize'
	 8: from /Users/cgunther/Code/exifr/lib/exifr/jpeg.rb:34:in `open'
	 7: from /Users/cgunther/Code/exifr/lib/exifr/jpeg.rb:34:in `block in initialize'
	 6: from /Users/cgunther/Code/exifr/lib/exifr/jpeg.rb:124:in `examine'
	 5: from /Users/cgunther/Code/exifr/lib/exifr/jpeg.rb:124:in `new'
	 4: from /Users/cgunther/Code/exifr/lib/exifr/tiff.rb:377:in `initialize'
	 3: from /Users/cgunther/Code/exifr/lib/exifr/tiff.rb:652:in `open'
	 2: from /Users/cgunther/Code/exifr/lib/exifr/tiff.rb:379:in `block in initialize'
	 1: from /Users/cgunther/Code/exifr/lib/exifr/tiff.rb:532:in `next'
/Users/cgunther/Code/exifr/lib/exifr/tiff.rb:528:in `next?': undefined method `<' for nil:NilClass (NoMethodError)
```

Trying to do some investigation myself, it seems part of the problem is that `pos` ends up being "22" here:
https://github.com/remvee/exifr/blob/828674312c0f833bb9e386c000489158576a6672/lib/exifr/tiff.rb#L497

But then the result of `@offset_next` is `nil`.

Then when it's used to in `#next`, we end up checking if `nil` is less than some other value, hence the error:
https://github.com/remvee/exifr/blob/828674312c0f833bb9e386c000489158576a6672/lib/exifr/tiff.rb#L528

My hunch is that maybe assigning `@offset_next` needs to fall back to a 0 when it'd otherwise be `nil` like `@offset_next = @data.readlong(pos) || 0` instead of:
https://github.com/remvee/exifr/blob/828674312c0f833bb9e386c000489158576a6672/lib/exifr/tiff.rb#L497

I've hit this issue on a number of user-uploaded images which I'm trying to optimize (via `https://github.com/toy/image_optim` which depends on this gem), though they've all come from the same user, implying something unique about how they're creating the images.

I don't know the first thing about EXIF/TIFF, though, otherwise I'd dig in to try to fix it properly.

Thanks for this gem and thanks in advance for your help.

![123_1012_300x_original](https://user-images.githubusercontent.com/107416/94064505-c853d080-fdb7-11ea-809d-c5e0a952c26e.jpg)

**Comment by remvee** [comment]
Thanks for reporting this!  The EXIF bit in the provided images seems truncated so it seems to be reading `nil`s instead of an offset to the next entry.  I fixed it (https://github.com/remvee/exifr/commit/f302e456136076edbdfe7262023bad693a10c31e) and plugged a couple more of these holes along the way.  I'll make a new release immediately.

**Comment by cgunther** [comment]
Thanks for the quick fix/release, that did the trick!
